### ISSUE TITLE
windbarb direction error

### ISSUE THREAD

**Issue by dankelley** [dankelley/windbarb#2]
"Another issue is that the wind directions do not look to be correct in many cases. As a test, they should line up with the wind arrows using the mapDirectionField(), which produces a good direction."

_Originally posted by @mdupilka in https://github.com/dankelley/windbarb/issues/1#issuecomment-2008357958_

**Comment by dankelley** [comment]
I have the sample data and the code given below does indeed make an erroneous fields.  I'll look into this, likely tomorrow.  In the meantime, I'll also email the data file (privately) to @richardsc.  (Click on Details to see the image and the code.)

<details>

![issue02](https://github.com/dankelley/windbarb/assets/99469/06a74c33-1f44-4a4b-b664-795e95bc5aba)


```R
library(oce)
source("wb.R")
load("exwindbarb.RData")
data(coastlineWorld)
if (!interactive()) png("issue02.png")
mapPlot(coastlineWorld,
    border = "black",
    col = "grey95",
    projection = "+proj=lcc +lat_0=63 +lat_1=33 +lat_2=45 +lon_0=-110",
    longitudelim = c(-140, -90), latitudelim = c(57, 70)
)

mapDirectionField(lons, lats,
    u = u,
    v = v,
    scale = .02,
    length = .08, code = 2, col = "red"
)

mapDirectionFieldBarbs(lons, lats,
    u = u,
    v = v,
    length = 1.5,
    code = 2, col = "blue"
)
if (!interactive()) dev.off()
```

**Comment by mdupilka** [comment]
Thanks for all the work.

**Comment by dankelley** [comment]
I made a reprex that is quite boiled-down.

It is in the repo, called `issue02b.R`. The results are as below. Obviously, I'm doing something really quite wrong!  I don't quite see how my previous examples made sense.  I set things up to be at 45 degrees, and also at 0 and 90 degrees.  I'll look into what is going on here.   Of course, I'll start with 0, 45 and 90 degrees.  Maybe I accidentally copied a `sin()` to a `cos()` or something nutty.

<details>

![issue02b](https://github.com/dankelley/windbarb/assets/99469/f5cf2686-8ae1-4a25-be8b-03f13a19875a)

**Comment by dankelley** [comment]
Rather than type a lot, I just made a video.  I will look into what silly error I'm making -- maybe using "x" where I want "y" in a trig calculation, etc.

https://github.com/dankelley/windbarb/assets/99469/2dc1bbc1-3ffd-4ffd-bdf7-80c2e31e593a

**Comment by dankelley** [comment]
I think I've figured it out but will not push to GH until tomorrow.

**Comment by dankelley** [comment]
I just pushed to GH.  If you do "make" on a unix machine it will create 3 PNG files.  The easiest to view is `issue02c.png`, because I set up scaling to give large enough elements to see.  It's below.

I think this issue -- as defined by its title, which is restrictive by design -- is ready to close.

The normal rule in oce is that the reporter closes, but in this case I reported it to save @mdupilka some trouble, so I request that he try these examples and add a comment here on whether it works or not.  (The file `issue02a.R` is his example with his data.  If the data are secret, I'll remove them from the repo.)

Also, Max, can you make a new issue about the NA values?  Just copy your content from #1, but in a new issue with a title that is restrictive and clear.  (Such titles are a great help to users.  In this case it's not critical since this repo is likely to be deleted soon, since we are getting close to being able to consider putting barbs into oce.)

![issue02c](https://github.com/dankelley/windbarb/assets/99469/95f30797-b913-497a-8869-1b53730d5135)

**Comment by dankelley** [comment]
Also, final check please, @mdupilka are the barbs pointed the right way, i.e. are they on the correct side. I think so, because I read somewhere that (in the N hemisphere) they point to low pressure, which is what they do (individually) in the picture in the prev comment.  I'd like to be sure on this long before putting any of this code into oce because oce is a large ship that is hard to turn.

**Comment by mdupilka** [comment]
Yes, the barbs are on the correct side. With the wind at your back they are on the left side, which is where the low pressure would be.

**Comment by mdupilka** [comment]
I just tested the latest d11fd5f]  version on my data I sent you. The barbs are right along the arrows as you saw.. Looks good. I will test it on other data. There is nothing secret about the data I sent you.

**Comment by mdupilka** [comment]
I tried it out on other data and the winds lines up right along the arrows.

**Comment by dankelley** [comment]
Solved.
