### ISSUE TITLE
consider adding this to oce

### ISSUE THREAD

**Issue by dankelley** [dankelley/windbarb#6]
I will do this sometime today.  I need to decide whether I want to make it be part of `mapDirectionField()`.  Frankly, I'm divided on that.  The docs on the latter can always point to a new function, after all. My problem with incorporating this is that then everything about the docs for `mapDirectionField()` has to be in the form "if `code` is `"barbs"`, then MEANING; otherwise MEANING".  That might be confusing.  I'll only know if I try to write the documentation and find it hard to organize.

* NOTE 1: the parameter I presently call `step` has no analogue to `mapDirectionField()`.  I guess I could add it to `mapDirectionField()` and just ignore it if the user wants barbs.  But I am still left with the impression that things will be made more complicated for users.
* NOTE 2: the `length` argument of `mapDirectionField()` could be used to set barb lengths.  I'll see how hard that might be in the code.  There are lots of spacing parameters that I have calibrated to look like what I have seen in documentation for wind barbs. GIving the user control over one of them might mess other things up, and then we might need another argument for the spacing between barbs, etc and so on.  And that's another function parameter that would be ignored except in this (rare) special case of wind barbs.

**Comment by dankelley** [comment]
Regarding length, I think that codes up easily.  The snapshots show for two different `length` values.  The spacing is adjusting well without another parameter, I think.  My idea is to default it to 0.2, as before.

**With length=0.2**

<img width="823" alt="Screenshot 2024-03-21 at 10 01 25 AM" src="https://github.com/dankelley/windbarb/assets/99469/b96d4700-8838-4634-93ff-2b3badb40ad8">


**With length=0.3**

<img width="820" alt="Screenshot 2024-03-21 at 10 01 05 AM" src="https://github.com/dankelley/windbarb/assets/99469/0ef3d8fb-ec20-4fcf-8bb5-8fa8837524eb">

**Comment by dankelley** [comment]
Regarding NOTE 1, a way to handle that is for `style="barb"` to use 10 units for the barb criterion, or e.g. `style="barb/5"` for 5 units.  (That is, `style="barb"` and `style="barb/10"` would be interpreted the same.)

**Comment by mdupilka** [comment]
I have tested the code and it works great. I see where you added the ok for the winds.

**Comment by dankelley** [comment]
I am adding it to oce -- not yet coded, nor pushed -- so I'm closing this.  PS. I see an issue with the demibarb computation, but I'll put an issue in oce, not here.
